### ISSUE TITLE
PHATE with non-PCA dimensionality reduction / denoised counts

### ISSUE THREAD

**Issue by andrewjkwok** [KrishnaswamyLab/PHATE#109]
Hi,

I've been looking to use this tool to visualise the structure in my dataset a bit better. I was wondering whether PHATE supports non-PCA dimensionality reductions, as my reading of the code and my attempts to use the tool seem to be that it starts with a count matrix after filtering/log (or square root) transformations, followed by PCA and then PHATE.

However, because my samples have batch effects, I've looked to use scVI to learn a latent space that has been batch corrected, and I have been using that latent space for kNN graph building/clustering/UMAP visualisation instead of principal components. Can I use that latent space for PHATE visualisation instead of the count matrix? Alternatively, could I use the denoised/normalised count matrix from scVI to input into PHATE for visualisation as per #105?

Many thanks in advance.

**Comment by nagendraKU** [comment]
Would appreciate an answer for this question. I am wondering the same, if one can use the scVI latent space instead of PCA to run PHATE.

**Comment by scottgigante** [comment]
You can use whatever latent space you wish as input to PHATE. Just pass in the data in the space you wish to use, and if it's more than 100 dimensions and you want to avoid additionally doing PCA, set n_pca=None.

**Comment by erzakiev** [comment]
@scottgigante is the requirement to have more than 100 dimensions a hard-type? I have an MNN-generated 50-dimensional space (and around 30k cells, if that's important), should I regenerate the MNN embedding with a higher number of dimensions?

**Comment by erzakiev** [comment]
@scottgigante I just realized that it automatically computes PCA if there are more than 100 dimensions, and if there are less, then it doesn't. Nice! My previous Q is irrelevant then
