### ISSUE TITLE
conda install phate fails

### ISSUE THREAD

**Issue by stanleyjs** [KrishnaswamyLab/PHATE#110]
**Describe the bug**
Can't install `phate` from `bioconda`.

**To Reproduce**
`mamba install -c bioconda phate`... mamba and conda are (mostly) interchangeable so this error should occur in `conda` as well.

**Expected behavior**
An installed version of phate
**Actual behavior**
````
Encountered problems while solving:
  - nothing provides graphtools >=1.3.1 needed by phate-0.4.5-py_0
````

</details>

I assume that graphtools is a pip requirement of phate.  It may be a version that got bumped and didn't get updated on pypi, or the pip requirement is specified as a conda requirement in the bioconda repo.

Just figured you guys should know. I can workaround it by building my own graphtools.

**Comment by scottgigante** [comment]
You need to have `conga-forge` in your channels list. 
```
mamba install -c bioconda -c condo-forge phate
```
should work.

**Comment by stanleyjs** [comment]
Oops! Thanks Scott.
