### ISSUE TITLE
PHATE gives "worse results" than UMAP

### ISSUE THREAD

**Issue by LaviCor** [KrishnaswamyLab/PHATE#123]
Hi all,
After finally getting around some technical difficulties I started experimenting with this amazing tool.
However, the results I get seem to be "worse" than what I get from UMAP in terms. 

I have scRNAseq data from three stages of embryonic development, which is visualized as continuous using UMAP (after harmony integration). When running PHATE on the whole dataset, the data is broken into three large groups of the developmental stages.
I know there are shared cell types between the three datasets, so I dont know why they are split like that...

Any help or tips on why this may happen and which parameters may resolve this issue would be great.
 
Example images:
UMAP embedding, group by time point:
![image](https://user-images.githubusercontent.com/101585799/207337032-0eecf9df-cf46-47d5-9eef-c3444ed0ba28.png)

PHATE embedding, group by time point:
![image](https://user-images.githubusercontent.com/101585799/207340383-0e8f8180-017f-4b4e-8f0c-7df0b61e9ffd.png)

**Comment by Alexgr97** [comment]
How many principle component dimensions are you feeding into UMAP? Are you using default parameters on PHATE?

Can you please show representative code that produced these images? (not everything, just what you ran as the final line for each of them should do for now)

Are these the exact same UMAP and PHATE dimensions plotted against each other? Or is one accidentally 1 x 2 and the other 1 x 3 etc?

**Comment by LaviCor** [comment]
@Alexgr97 
> How many principle component dimensions are you feeding into UMAP? Are you using default parameters on PHATE?
> 
- 30 dims were used for UMAP (which was created using harmony integrated values). This wasn't created using PHATE default parameters, but they give pretty much the same result.

> Can you please show representative code that produced these images? (not everything, just what you ran as the final line for each of them should do for now)
> 
- UMAP visualization was done simply with 
" DimPlot(fap.seurat, reduction = 'umap_harmony', label = F, repel = T, group.by = 'orig.ident') "
However, I did not use the default code to run phate, but rather a modified one taken from https://github.com/mckellardw/scMuscle/blob/main/R_scripts/2_myogenic_analysis_v1.R which used PHATE on a large scale integration dataset. 
The relevant lines were
"# Run PHATE on harmony values ####

tmp.phate <- phate(
  t(GetAssayData(fap.seurat,slot="data"))
) 
colnames(tmp.phate$embedding) <- paste0("phate_", 1:2)
tmp.phate$params$data <- NULL

fap.seurat[["phate"]] <- CreateDimReducObject(
  embeddings = tmp.phate$embedding,
  key = "phate_", 
  assay = 'RNA',
  misc = tmp.phate$params
)

DimPlot(
  fap.seurat,
  reduction='phate',
  cells = sample(colnames(fap.seurat)),
  group.by="orig.ident",
  repel = T,label=T
) +
  NoLegend() +
  labs(x="PHATE_harmony_1",y="PHATE_harmony_2")
"

> Are these the exact same UMAP and PHATE dimensions plotted against each other? Or is one accidentally 1 x 2 and the other 1 x 3 etc?
- not sure I got your last question, the data was ploted using Dimplot(reduction = UMAP), then the same object was used for phate analysis.

**Comment by Alexgr97** [comment]
hi,

okay - so you've used 30 principal components in your UMAP


but your code for running phate appears to me to be "tmp.phate <- phate(
t(GetAssayData(fap.seurat,slot="data"))
)"?

This will run with the default params, which are 100 components

so this might explain why you're seeing thsi difference, as once you get to the actual algorithmic differences between UMAP and PHATE, they're working with different inputs (in terms of the # of PCA dims). so perhaps actually there is a lot of useful informatino for separating these clusters between your 30 th and 100th PCs? How did you select your dims # for input to UMAP?

what i meant was, as you have removed teh axes on those images, can we please check that they are UMAP_1 x UMAP_2, in terms of x and y, and that the same PHATE1 x PHATE2 have been plotted as x and y, rather than it being UMAP_3 or PHATE3. But your code above answers that for me

**Comment by LaviCor** [comment]
@Alexgr97 
You are completely right! I had missed that this code did in fact not use the integrated values (as pointed on this thread https://github.com/mckellardw/scMuscle/issues/7 by David McKellar which I found after posting this question)

Running PHATE again using Harmony integrated values provided a very nice continuous data.

Thank you very much for your help!
