### ISSUE TITLE
Install issue, probably sklearn -> scikit-learn versions

### ISSUE THREAD

**Issue by bbimber** [KrishnaswamyLab/PHATE#124]
We are having errors installing phate, and I think it tracks back to here, and to updates in scikit-learn. I posted details in the graphtools repo: https://github.com/KrishnaswamyLab/graphtools/issues/64.

I believe scikit-learn 1.2.0 breaks graphtools /PHATE. Have you seen this issue? Thanks in advance.

**Comment by JH1606-code** [comment]
Hi,

I run in to the same issue. Do you have any idea how to fix this problem, yet?

Thanks in advance.

**Comment by bbimber** [comment]
A workaround is something like:
```
pip3 install scikit-learn==1.1.3 
```

to force the older scikit-learn version

**Comment by JH1606-code** [comment]
Thank you for your feedback. I could also fix the error with this.

**Comment by scottgigante** [comment]
Thanks for the report!
