### ISSUE TITLE
Can phate support a higher version of pandas?

### ISSUE THREAD

**Issue by caodudu** [KrishnaswamyLab/PHATE#137]
The pre-processing tool used in `PHATE` seems to be the `scprep` which developed by you too. However, `scprep` is still accepting `pandas` with the maximum version number of 1.4. Consider that many single-cell tools have been updated to the advanced version of `pandas`. This may lead to incompatibilities. Have you considered updating `PHATE` to a higher version?

**Comment by scottgigante** [comment]
@caodudu thanks for raising this! I've released a new version of scprep (1.2.3) which should solve your issue.
