### ISSUE TITLE
2.7 vs 3.5 difference for testing w/ DLA fractal tree

### ISSUE THREAD

**Issue by DylanM-Marshall** [KrishnaswamyLab/PHATE#20]
Heads up: I copied code block on README.md for running the test script on the DLA fractal tree and got the following error...

`~/p36/lib/python3.6/site-packages/phate/phate.py in calculate_kernel(data, k, a, alpha_decay,`
`knn_dist, verbose, ndim, random_state, n_jobs)`

`ValueError: Unknown format code 'd' for object of type 'float'`

Not a big deal and seems easily resolvable. Likely the case that bugs w.r.t. different python versioning could affect user experience. 

Was installed via: 

`pip3.6 install phate`

**Comment by scottgigante** [comment]
Thanks for the bug report! I've changed these to modern formatting, hopefully that should be resolved.

**Comment by scottgigante** [comment]
Uploaded as `v0.2.3` to PyPi.
