### ISSUE TITLE
GIF-inate the output?

### ISSUE THREAD

**Issue by DylanM-Marshall** [KrishnaswamyLab/PHATE#22]
I'd imagine some users would like a GIF of the output? Maybe it's just me... but honestly, tell me the below is not cool!

![3d_phate](https://user-images.githubusercontent.com/12707356/39677188-b5883e72-5144-11e8-807f-117f01d606e9.gif)

starter code taken from: https://bit.ly/2JUkoOv ...

[example.txt](https://github.com/KrishnaswamyLab/PHATE/files/1977990/example.txt)

**Comment by DylanM-Marshall** [comment]
Python 3.6, jupyter Lab, here is my `pip3.6 freeze` - FYI.
[packages.txt](https://github.com/KrishnaswamyLab/PHATE/files/1977988/packages.txt)

**Comment by scottgigante** [comment]
Thanks Dylan, this is awesome! I would want to check how this interacts with Jupyter notebooks since a lot of our users run PHATE interactively (and I know there are some quirks with matplotlib/jupyter inline animations) but I see no reason not to include a function that does this.

**Comment by DylanM-Marshall** [comment]
This is true - lots of potential incompatibility bugs. FYI, the above was made in a Jupyter Lab notebook. I just copied the code/methods to a .txt file. 

It might be a stretch to do so, and I already mentioned it to Kevin while I was in New Haven but I think a GIF of PHATE in action as it clusters the data would be cool. Perhaps not actually informative, but potentially aesthetically pleasing? i.e. https://bit.ly/2JUTBBF

**Comment by scottgigante** [comment]
Not a stretch at all! I think that would be a great way of demonstrating how the choice of `t` affects the embedding. Although in practice most users will use the automatic selection, it's good to have it depicted for those who are interested. I'll comment here when I have a chance to put something like this together.
