### ISSUE TITLE
couple of suggestions post-tutorial

### ISSUE THREAD

**Issue by DylanM-Marshall** [KrishnaswamyLab/PHATE#23]
1) Alternative to log or sqrt for "potential_method" - a nice compromise could be the [inverse hyperbolic sine function](http://mathworld.wolfram.com/images/interactive/ArcSinhReal.gif). Continuous from neg. inf. to pos. inf. and exhibits logarithmic properties asymptotically - therefore log-scales values without need for imputation. 

    - Others in the bioinformatics field have begun using this transformation, e.g: [Michael Hoffman](https://twitter.com/michaelhoffman/status/707252800359686144) at U. Toronto. 

2) Mysterious cell in the "remove rare cells" cell - probably is just a mistake?

     - `genes_keep=sum(data)>10;  data=data(:,genes_keep); genes=genes(genes_keep)`

3) Alternative method for getting users introduced to method - have the tutorial be housed in a Google CoLab setting, i.e: https://colab.research.google.com/. This would remove any barrier to installation as a user goes through a first pass. Of course, afterwards, they would still need to install it and all that that entails. Distill.pub uses CoLab notebooks to allow interested readers to do exactly this - https://distill.pub/2018/building-blocks/.

**Comment by DylanM-Marshall** [comment]
Also, building on the previous GIF - suggestion in the other issue thread, using labels and a different coloring scheme, PHATE applied to the tutorial's example data could be slightly more visually compelling. It seems reasonable to me that a user (read, biologist) would want to see how the different time point's data splays along the PHATE axes. Converting the time points then from their matrix representation to explicit "Days" of extraction and using a color scheme that is diverging (perhaps pulled from here - http://colorbrewer2.org/) better depicts this progression.

```fig = plt.figure(figsize=(12, 12))
ax = fig.add_subplot(111, projection='3d')

ax.scatter(
    xs=Y_2Dmmds[:, 0], 
    ys=Y_2Dmmds[:, 1], 
    zs=Y_2Dmmds[:, 2],
    c=_y,
    s=1.28)

ax.set_xticks([]); ax.set_yticks([]); ax.set_zticks([])
ax.set_xlabel('PHATE 1', fontsize=16)
ax.set_ylabel('PHATE 2', fontsize=16)
ax.set_zlabel('PHATE 3', fontsize=16)

ax.text(-10, 0, -20, 'Day 0', color='#fc8d59', fontsize=16, fontweight='bold')
ax.text(-5, 0, -20, 'Day 6', color='#fee08b', fontsize=16, fontweight='bold')
ax.text(0, 0, -20, 'Day 12', color='#dae69c', fontsize=16, fontweight='bold')
ax.text(5, 0, -20, 'Day 18', color='#99d594', fontsize=16, fontweight='bold')
ax.text(10, 0, -20, 'Day 24', color='#3288bd', fontsize=16, fontweight='bold')

angles = np.linspace(0, 360, 129)[:-1]
rotanimate(ax, angles,'3d_scRNAseq_phate.gif', delay=8)```

**Comment by DylanM-Marshall** [comment]
Also, a consistent question that pops up when I show biologists these outputs is... what does a PHATE axis mean? Said differently, a PCA axis represents covariation, would the elevator-pitch for PHATE be that it is depicting "diffusion potential" ... ? A sort-of succinct and sexy summation of what the axes represent could sell the method! t-SNE itself, though used so heavily these days, have axes that aren't really "explainable".

**Comment by scottgigante** [comment]
Hi Dylan, apologies I missed this! These sorts of enhancements would definitely be worth adding - I especially like the idea of hosting on Google Colab. I'd rather leave this as open until it reaches the top of the priority list, if that's alright with you!

**Comment by DylanM-Marshall** [comment]
Yeah, no worries! Indeed, CoLab is a pretty slick tool. I'm kinda new to the unspoken rules of 'Github issues', closed it because the above doesn't seem like an "issue" - but your call!

**Comment by scottgigante** [comment]
Fixed :)
