### ISSUE TITLE
Add to PyPI

### ISSUE THREAD

**Issue by hammer** [KrishnaswamyLab/PHATE#3]
It would be nice to make PHATE installable via a package manager like pip.

**Comment by dburkhardt** [comment]
Hi Jeff, thanks for the suggestion! We're still working on getting more of the auxiliary code implemented in python (see #2) and would like to upload a more complete version to PyPI once those components are finished. Would it be more helpful for you if we uploaded the current state now?

**Comment by scottgigante** [comment]
@hammer as of May 2018 PHATE is now on PyPi at https://pypi.org/project/phate/
