### ISSUE TITLE
An issue with using scHi-C with PHATE

### ISSUE THREAD

**Issue by tarak77** [KrishnaswamyLab/PHATE#35]
@kmoon3 @scottgigante The problem with using binary contact maps with 1 along the diagonals as input to PHATE(using default parameters) is that a compact(kinda globular) structure is obtained. We do not want that! So I think this points to: first impute the missing values(due to very sparse single cell Hi-C data) by using MAGIC before applying PHATE?

I tried to use PHATE on chromosomes for cell 1 and cell 2 from https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE80280. At the bottom of that page we use GSE80280_RAW.tar custom file.

In that, the RAW results typically lists a number of observed contacts between specific genome positions. From the raw results, the contacts were aggregated into equally spaced bins along the chromosomes. I worked with a bin size of 50 kbp. Then all observed contacts were assigned to their corresponding bins. In the case that multiple contacts fell into the same bin, the duplicate entries were ignored so that a binary contact matrix C_ij was obtained for each chromosome. Hence, C_ij = 1 represents a Hi-C contact between bins i and j, while C_ij = 0 represents the absence of a contact.

An example file for cell-1 chr1 is below:
The first row list the #bins and #contacts
[GSM2219497_cell1_chr1_50kb.txt](https://github.com/KrishnaswamyLab/PHATE/files/2113163/GSM2219497_cell1_chr1_50kb.txt)

After removing bins with no interactions, the binary contact matrix for the same chr1 is:
[contact_cell1_chr1.txt.tar.gz](https://github.com/KrishnaswamyLab/PHATE/files/2113161/contact_cell1_chr1.txt.tar.gz)

Any help would be greatly appreciated!
Thanks,
-Tarak
@tarak77

**Comment by dburkhardt** [comment]
As there hasn't been any activity here in over a month, I'm closing this issue.
