### ISSUE TITLE
A doubt in the Proposition 1 from PHATE paper

### ISSUE THREAD

**Issue by tarak77** [KrishnaswamyLab/PHATE#43]
Hello,

This question may seem odd but I had a doubt in s statement made in Proposition 1 of PHATE paper:
**Furthermore, it can be verified that the left and right eigenvectors of Pε are related by ψi(y) = φi(y)ψ0(y),** 
How can we relate them? I am trying to figure it out but I am not successful yet.

Any help is great!

**Comment by scottgigante** [comment]
Hi @tarak77 , 

Here's the explanation courtesy of Guy Wolf:

> The left and right eigenvectors are related via the symmetric conjugate A = D^{1/2} P D^{-1/2} where D are the degrees of P. Since A is symmetric, it's left and right eigenvectors are the same, say we call them u_0, u_1. ... , then because of the conjugation it's easy to see that D^{1/2} u_i are right eigenvectors of P and D^{-1/2} u_i are left eigenvectors, and under normalization this can be done also by using the stationary distribution rather than degrees. Finally, the first left eigenvector of P is the stationary distribution, so this yields the written expression.

I hope this helps.

**Comment by tarak77** [comment]
Got it. Thanks @scottgigante !
