### ISSUE TITLE
Running PHATE with verbose = False still prints MDS stress

### ISSUE THREAD

**Issue by dburkhardt** [KrishnaswamyLab/PHATE#52]
Running PHATE with `verbose = False` still prints MDS stress

breaking at iteration 103 with stress 1322.9503670967915
breaking at iteration 533 with stress 79.50760126313087
breaking at iteration 217 with stress 54.46123952246649
breaking at iteration 148 with stress 143.56729643278047

**Comment by scottgigante** [comment]
Tuns out sklearn's MDS function is more verbose with `verbose=-1` than with `verbose=0`. Fix will be included in the next release.
