### ISSUE TITLE
phateR: TypeError: __init__() got an unexpected keyword argument 'n_landmark' 

### ISSUE THREAD

**Issue by ryetochondria** [KrishnaswamyLab/PHATE#61]
> Error in py_call_impl(callable, dots$args, dots$keywords) : 
>   TypeError: __init__() got an unexpected keyword argument 'n_landmark'

**Command traceback shows typo? (n_landmark = n.landmark)**
`pyphate$PHATE(n_components = ndim, k = k, a = alpha, t = t, n_landmark = n.landmark, gamma = gamma, n_pca = npca, mds = mds.method, mds_dist = mds.dist.method, knn_dist = knn.dist.method, n_jobs = n.jobs, random_state = seed, verbose = verbose)`

**Comment by scottgigante** [comment]
@ryetochondria what version of PHATE do you have installed? Can you please run `pip install --upgrade phate`, or, if necessary, `pip install --user --upgrade phate` and try again?
