### ISSUE TITLE
Add `n_clusters = 'auto'` e.g. using silhouette score

### ISSUE THREAD

**Issue by sameet** [KrishnaswamyLab/PHATE#65]
Hi,

I am trying to figure out how to decide number of clusters to be produced.  I have a data-set where I have used Seurat, and Seurat was able to detect 17 clusters.  Is there a way for me to use PHATE in a similar way.   

Sameet

**Comment by scottgigante** [comment]
Hi Sameet, unfortunately selecting the "right" number of clusters is a very difficult problem. There are some heuristics you can use such as the Silhouette score, AIC and BIC. You can read about this problem on [Wikipedia](https://en.wikipedia.org/wiki/Determining_the_number_of_clusters_in_a_data_set). If you decide on a heuristic that works for you, you can apply whatever clustering method with automatic cluster selection to `phate_op.diff_potential`, which is what we apply `kmeans` to for clustering on PHATE.

**Comment by dburkhardt** [comment]
Sounds like we should include a heuristic for PHATE though. Also, can we change the API to be `n_clusters` not `k` for `phate.cluster.kmeans`?

**Comment by scottgigante** [comment]
@dburkhardt would you be willing to test out Silhouette / AIC / BIC to see which seems to produce the best results for our purposes? I'd be happier to include this if we were confident it would produce reasonable results.

Re: the API change, I'm happy to do that now.
