### ISSUE TITLE
EmbryoidBody.ipynb

### ISSUE THREAD

**Issue by sameet** [KrishnaswamyLab/PHATE#67]
In the plotting part the `cmap` should be `Spectral`, not `spectral`.

**Comment by scottgigante** [comment]
From what I can see this is already the case. Can you please point to the line where it is missing the upper case S?

**Comment by sameet** [comment]
My bad,  I mixed up to documents.  It is indeed "S".

**Comment by scottgigante** [comment]
No problem, I appreciate you opening issues! Keep them coming :)
