### ISSUE TITLE
Stuck after Installatation of phateR.

### ISSUE THREAD

**Issue by MQMQ2018** [KrishnaswamyLab/PHATE#77]
Dear Dr. Smita, 

After I installing the phateR by Guided turorial in R and also installing the magic-impute in python=3.6. I encountered the conflict in running R as below, does anyone could give me some guidance how to solve it? Thank you so much.

```
library(dplyr)
library(ggplot2)
library(Matrix)
library(readr)
library(viridis)
library(Rmagic)
library(phateR)
library(Seurat)
...
> dataPhate=phate(t(data),n.landmark = NULL,n.jobs=-2)
Calculating PHATE...
  Running PHATE on 377 cells and 10806 genes.
  Calculating graph and diffusion operator...
    Calculating PCA...
    Calculated PCA in 0.73 seconds.
    Calculating KNN search...
    Calculated KNN search in 0.16 seconds.
    Calculating affinities...
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: __init__() got an unexpected keyword argument 'mds_solver'

Detailed traceback: 
  File "/home/mq2019/.local/lib/python3.7/site-packages/phate/phate.py", line 835, in fit_transform
    self.fit(X)
  File "/home/mq2019/.local/lib/python3.7/site-packages/phate/phate.py", line 740, in fit
    **(self.kwargs))
  File "/home/mq2019/.local/lib/python3.7/site-packages/graphtools/api.py", line 248, in Graph
    return Graph(**params)
  File "/home/mq2019/.local/lib/python3.7/site-packages/graphtools/graphs.py", line 102, in __init__
    super().__init__(data, n_pca=n_pca, **kwargs)
  File "/home/mq2019/.local/lib/python3.7/site-packages/graphtools/base.py", line 750, in __init__
    super().__init__(data, **kwargs)
  File "/home/mq2019/.local/lib/python3.7/site-packages/graphtools/base.py", line 135, in __init__
    super().__init__(**kwargs)
  File "/home/mq2019/.local/lib/python3.7/site-packages/graphtools/base.py", line 373, in __init__
    super().__init__(**kwargs)
In addition: Warning message:
In on_load() :
  Python PHATE version 0.4.4 is out of date (recommended: 1.0). Please update with pip (e.g. pip install --upgrade phate) or phateR::install.phate().
```

And after I got this messenge, I tried to do "pip install --upgrade phate" and got updated phate as result as below:
```
(PhateAndMagic) [mq2019@comet-ln2 phateRAnalysis-FC22samples_Oli]$ pip show phate meld magic-impute
Name: phate
Version: 1.0.0
Summary: PHATE
Home-page: https://github.com/KrishnaswamyLab/PHATE
Author: Daniel Burkhardt, Krishnaswamy Lab, Yale University
Author-email: daniel.burkhardt@yale.edu
License: GNU General Public License Version 2
Location: /home/mq2019/miniconda2/envs/PhateAndMagic/lib/python3.6/site-packages
Requires: scikit-learn, scprep, Deprecated, tasklogger, sgdpy, numpy, graphtools, matplotlib, scipy, future
Required-by: 
---
Name: meld
Version: 0.2.4
Summary: MELD
Home-page: https://github.com/KrishnaswamyLab/MELD
Author: Daniel Burkhardt, Krishnaswamy Lab, Yale University
Author-email: daniel.burkhardt@yale.edu
License: Dual License - See LICENSE file
Location: /home/mq2019/miniconda2/envs/PhateAndMagic/lib/python3.6/site-packages
Requires: numpy, scprep, pygsp, scipy, graphtools, pandas
Required-by: 
---
Name: magic-impute
Version: 2.0.3
Summary: MAGIC
Home-page: https://github.com/KrishnaswamyLab/MAGIC
Author: 
Author-email: 
License: GNU General Public License Version 2
Location: /home/mq2019/.local/lib/python3.6/site-packages
Requires: numpy, matplotlib, scprep, scikit-learn, graphtools, scipy, tasklogger, future, pandas
Required-by: 
```

And I also run phateR::install.phate() in R, but got stuck as result as below:
```
  Using cached https://files.pythonhosted.org/packages/e7/f9/f0b53f88060247251bf481fa6ea62cd0d25bf1b11a87888e53ce5b7c8ad2/pytz-2019.3-py2.py3-none-any.whl
ERROR: meld 0.2.3 has requirement pandas<0.24, but you'll have pandas 0.25.3 which is incompatible.
ERROR: magic-impute 1.5.5 has requirement pandas<0.24,>=0.21.0, but you'll have pandas 0.25.3 which is incompatible.
Installing collected packages: numpy, scipy, six, python-dateutil, pyparsing, setuptools, kiwisolver, cycler, matplotlib, pytz, pandas, decorator, joblib, scikit-learn, scprep, sgdpy, future, tasklogger, pygsp, graphtools, wrapt, Deprecated, phate
Successfully installed Deprecated-1.2.7 cycler-0.10.0 decorator-4.4.1 future-0.18.2 graphtools-1.4.1 joblib-0.14.0 kiwisolver-1.1.0 matplotlib-3.0.3 numpy-1.17.4 pandas-0.25.3 phate-1.0.0 pygsp-0.5.1 pyparsing-2.4.5 python-dateutil-2.8.1 pytz-2019.3 scikit-learn-0.22 scipy-1.3.3 scprep-1.0.3 setuptools-42.0.2 sgdpy-1.4.1 six-1.13.0 tasklogger-1.0.0 wrapt-1.11.2
Install complete. Please restart R and try again.
```

If possible, could you help to give me some tips how to overcome this error? Thank you so much.
Best,
Qi

**Comment by JackieShen68** [comment]
I have similar issues. Could you please help? @SmitaKrishnaswamy Lab
Thank you very much!

**Comment by scottgigante** [comment]
@MQMQ2018 it looks like your installations of MELD and MAGIC are out of date. Please run the following:
```
pip install --upgrade meld magic-impute phate
```
and then in a new R session, run the following:
```
reticulate::py_discover_config("phate")
```
and paste the output here.

**Comment by MQMQ2018** [comment]
Thank you for your response. 
The output is below:
#===#
reticulate::py_discover_config("phate")
> reticulate::py_discover_config("phate")
python:         /home/mq2019/miniconda2/envs/r-reticulate/bin/python
libpython:      /home/mq2019/miniconda2/envs/r-reticulate/lib/libpython3.7m.so
pythonhome:     /home/mq2019/miniconda2/envs/r-reticulate:/home/mq2019/miniconda2/envs/r-reticulate
version:        3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21)  [GCC 7.3.0]
numpy:          /home/mq2019/.local/lib/python3.7/site-packages/numpy
numpy_version:  1.17.2
phate:          /home/mq2019/.local/lib/python3.7/site-packages/phate

python versions found: 
 /home/mq2019/miniconda2/envs/r-reticulate/bin/python
 /home/mq2019/miniconda2/envs/PhateAndMagic/bin/python
 /usr/bin/python
 /opt/python/bin/python
 /opt/python/bin/python3
 /home/mq2019/miniconda2/envs/HOMER/bin/python
 /home/mq2019/miniconda2/envs/S/bin/python
 /home/mq2019/miniconda2/envs/SnapATAC/bin/python
 /home/mq2019/miniconda2/bin/python
> 
#===#
Thank you so much. 

Best,
Qi

**Comment by scottgigante** [comment]
That's a lot of versions of Python! If you want to use the one you've named after PHATE (` /home/mq2019/miniconda2/envs/PhateAndMagic/bin/python`), then you should run
```
reticulate::use_python("/home/mq2019/miniconda2/envs/PhateAndMagic/bin/python")
```
before you run `library(phateR)`, and then make sure that PHATE is installed in that version with
```
/home/mq2019/miniconda2/envs/PhateAndMagic/bin/python -m pip install --upgrade phate meld magic-impute
```

Alternatively, if you want to avoid changing the version of Python that `reticulate` uses, you could make sure that PHATE is installed on that one:
```
 /home/mq2019/miniconda2/envs/r-reticulate/bin/python -m pip install --upgrade phate magic-impute meld
```

Read more about choosing which version of Python is used by `reticulate`: https://rstudio.github.io/reticulate/articles/versions.html

The important part is that when you run `pip install --upgrade phate`, that this `pip` is linked to the same `python` that is running from R.

**Comment by MQMQ2018** [comment]
Thank you Scott, It really helps a lot.
I learnt from it.  Thank you so much!

Best,
Qi
