### ISSUE TITLE
Randomization in results generation

### ISSUE THREAD

**Issue by Winnie09** [KrishnaswamyLab/PHATE#81]
Hi,

I applied PHATE on the same dataset twice with the exact same codes and get two different results. Is there any part that include randomization and I need to set seed? Thanks!

Winnie

**Comment by scottgigante** [comment]
Hi @Winnie09 , generally we find the results are fairly consistent across runs, but there are some numerical issues that can lead to slight differences. If you would like to rerun PHATE with exactly the same output every time, you can set the `random_state` parameter (or `seed` in R).

**Comment by Winnie09** [comment]
OK. Thank you!
