### ISSUE TITLE
Using PHATE with multi-batch single-cell data

### ISSUE THREAD

**Issue by syouligan** [KrishnaswamyLab/PHATE#82]
Hi there

I was wondering if there had been any developments on how to integrate batch information and correction into PHATE analysis? Specifically, PHATE tutorials import data from multiple batches yet don't quite address data merging/correction of batch effects.

We are working with a single cell data generated in multiple batches which we merge using the [fastmnn](https://rdrr.io/github/LTLA/batchelor/man/fastMNN.html) approach. This produces "batch-corrected" expression values and low-dimensional coordinates for visualisation. Is there a way these tools may be able to be used together?

Thanks for the great work.

**Comment by scottgigante** [comment]
Hi @syouligan ,

It is perfectly possible to use the batch corrected expression values as input to PHATE. There is an alternative semi-supported workflow that we use internally which does something similar but is more integrated, which runs as follows:

```
import graphtools
import phate
import scprep

data1 = ... # load your data per batch
data2 = ...
data_combined, sample_labels = scprep.utils.combine_batches([data1, data2], batch_labels=['1', '2'])
# sample_labels is a list of batch names, one for each cell

mnn_graph = graphtools.Graph(data_combined, n_pca=100, sample_idx=sample_labels, kernel_symm='mnn')
phate_op = phate.PHATE()
phate_data = phate_op.fit_transform(mnn_graph)
```

**Comment by syouligan** [comment]
Excellent, thanks very much!
