### ISSUE TITLE
Ability to supply custom distance matrix? (not just method)

### ISSUE THREAD

**Issue by wallacelab** [KrishnaswamyLab/PHATE#90]
(working in python version) PHATE currently allows the user to set a distance metric using the `knn_dist` and `mds_dist` parameters. Is there a way to supply a pre-computed distance matrix instead, or would this be difficult to implement?

My reasoning is that I work with microbiome data, and I often use the Unifrac distance metrics, which include correction for phylogenetic distance. There's no easy way to integrate these into the current PHATE pipeline, so being able to supply a pre-computed matrix instead of just a method would be beneficial.

Thank you.

**Comment by scottgigante** [comment]
Hi @wallacelab , thanks for using PHATE!

From [the docs](https://phate.readthedocs.io/en/stable/api.html#module-phate.phate):

> knn_dist (string, optional, default: 'euclidean') – recommended values: ‘euclidean’, ‘cosine’, ‘precomputed’ Any metric from scipy.spatial.distance can be used distance metric for building kNN graph. Custom distance functions of form f(x, y) = d are also accepted. **If ‘precomputed’, data should be an n_samples x n_samples distance or affinity matrix. Distance matrices are assumed to have zeros down the diagonal, while affinity matrices are assumed to have non-zero values down the diagonal. This is detected automatically using data[0,0]. You can override this detection with knn_dist=’precomputed_distance’ or knn_dist=’precomputed_affinity’.**

**Comment by wallacelab** [comment]
Excellent, I missed that. Thank you!
