### ISSUE TITLE
Coloring cells by pseudo-time

### ISSUE THREAD

**Issue by ashwinikumarkulkarni** [KrishnaswamyLab/PHATE#92]
Hello! I recently started getting in to using PHATE. I am wondering if one can color the cells on PHATE scatter plot by pseudo-time instead of a gene or known time-points across the data. Similarly, how to split the PHATE data into various states across pseudo-time? Thanks!

**Comment by dburkhardt** [comment]
Hi @ashwinikumarkulkarni, you certainly can do this using matplotlib or scprep. See scprep examples here: https://scprep.readthedocs.io/en/stable/examples/scatter.html

You also might also find the matplotlib pyplot tutorials helpful. They cover this kind of content: https://matplotlib.org/users/pyplot_tutorial.html

Finally, if you look at our Python Tutorial notebook you'll see examples of this kind of plot.

**Comment by ashwinikumarkulkarni** [comment]
Thanks @dburkhardt ! I will look into it. Do you have any suggestion for similar implementation using R?

**Comment by dburkhardt** [comment]
Check out https://dynverse.org/

**Comment by ashwinikumarkulkarni** [comment]
Thank you for suggesting the dynverse. I will check that too. I am still confused about how to integrate the PHATE into PAGA (Scanpy) or something else in order to get the PHATE plot colored by pseudo time. scanpy.external seem to have phate incorporated. Is there any specific tutorial available for that implementation. Thanks!
