### ISSUE TITLE
EBdatamat

### ISSUE THREAD

**Issue by ShobiStassen** [KrishnaswamyLab/PHATE#94]
Hi, I just have a quick question about the EBdata.mat file in the Data folder. Is this processed the same was as the in the PHATE Jupyter NB? It seems like the genes/cells have been filtered, but not yet normalized or transformed ?
Thanks so much

**Comment by scottgigante** [comment]
You are correct! This is indeed processed in the same way as in the Jupyter notebook. It has been filtered but not normalized or transformed.
